apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    environment: test
spec:
  containers:
  - name: ponnam-devops
    image: iponnam/devops:latest
    ports:
    - name: http
      containerPort: 8080