apiVersion: v1
kind: Pod
metadata:
  name: test-pod-02
  labels:
    environment: test
spec:
  containers:
  - name: ponnam-devops-02
    image: iponnam/devops:latest
    ports:
    - name: http
      containerPort: 8080
  nodeSelector:
    environment: test
