apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-01
  labels:
    environment: dev
spec:
  containers:
  - name: ponnam-devops
    image: iponnam/devops:latest
    ports:
    - name: http
      containerPort: 8080
  nodeSelector:
    environment: dev
