apiVersion: v1
kind: Pod
metadata:
  name: ponnam-pod
  labels:
    zone: dev
    version: v1
spec:
  containers:
  - name: ponnam-devops
    image: iponnam/devops:latest
    ports:
    - name: http
      containerPort: 8080
      hostPort: 81