apiVersion: v1
kind: Pod
metadata:
  name: nignix-pod
  labels:
    zone: dev
    version: v1
spec:
  containers:
  - name: nginx-devops
    image: nginx:latest
    ports:
    - name: http
      containerPort: 80